#include "SystemImplementations.h"

DEFINE_SYSTEM_ID(TestSystem1);
DEFINE_SYSTEM_ID(TestSystem2);
DEFINE_SYSTEM_ID(TestSystem3);
DEFINE_SYSTEM_ID(TestSystem4);
DEFINE_SYSTEM_ID(TestSystem5);
DEFINE_SYSTEM_ID(TestSystem6);
DEFINE_SYSTEM_ID(TestSystem7);
DEFINE_SYSTEM_ID(TestSystem8);

ECS_REGISTER_SYSTEM(TestSystem1);
ECS_REGISTER_SYSTEM(TestSystem2);
ECS_REGISTER_SYSTEM(TestSystem3);
ECS_REGISTER_SYSTEM(TestSystem4);
ECS_REGISTER_SYSTEM(TestSystem5);
ECS_REGISTER_SYSTEM(TestSystem6);
ECS_REGISTER_SYSTEM(TestSystem7);
ECS_REGISTER_SYSTEM(TestSystem8);